erp:
  authp:
      roles: 
      -
        role: Adviser
        permissions:
              - hello
              - test
      -
        role: Admin
        permissions:
              - hello
              - test
 